### PR TITLE
Feature/back end service setup

### PR DESCRIPTION
**Pull request by deadwing88**

### CODE REVIEW

**Comment by daveismith** [comment]
Sweet. I can get this running. Once comment I had was that we had talked about partitioning the backend and frontend. I had pictured a root sort of setup as

backend/
docker-compose.yaml
docs/
frontend/

Completely fine to do it another way, but wanted to make sure we're thinking of setting this up correctly.

**Comment by deadwing88** [comment]
> Sweet. I can get this running. Once comment I had was that we had talked about partitioning the backend and frontend. I had pictured a root sort of setup as
> 
> backend/
> docker-compose.yaml
> docs/
> frontend/
> 
> Completely fine to do it another way, but wanted to make sure we're thinking of setting this up correctly.

I can change to this structure, no problem. Another way I've seen this done is to build the front end right into the dotnet core solution like this...

https://blog.maartenballiauw.be/post/2019/11/13/how-does-the-aspnetcore-spa-development-experience-work.html

That way you can run both the frontend and backend in the same container.

**Comment by daveismith** [comment]
Ah, Ok. I didn't realize that VS was quite that integrated for React. I'm not sure I think running the frontend and backend in the same container is beneficial. Typically I would want to host static files, etc. using either a container tuned for that or something designed for file hosting rather than running code. This would also be because the front end and backend will probably need to scale differently as well.

Is the single container approach from MS recommended for production?

**Comment by deadwing88** [comment]
I think it is just for convenience. Let's keep them separate.

**Review by daveismith — APPROVED** [review]
LGTM. Thanks for all the work to start this off.

**Review by timlaengert — APPROVED** [review]
Looks good!

**Pull request merged**
