### PR TITLE
Schema Design

### PR DESCRIPTION
**Pull request by daveismith**
This is the initial schema design. It's based on protobufs and grpc. Essentially the expectation is that at the start of the game the player will call JoinGame which will return a stream over which all unsolicited messages are returned.

I haven't tested this yet with any sort of linter, visualization tool or codegen but it should give a rough idea of what I'm thinking of. There are minor changes compared to our initial flowchart in terms of message content as I made the assumption the server will have the context of which client the request is coming from or the control of which client a message is going to.

### CODE REVIEW

**Review by timlaengert — APPROVED** [review]
Thanks David, looks good to me I think.  Only comment would be maybe it's worth starting the Rank enum at 9 instead of 0?  I've seen a one-deck four-player variation that includes 7s and 8s, maybe we'd want to leave room to expand if needed?

**Comment by daveismith** [comment]
The enumerated values need to start at 0 unfortunately.

**Comment by timlaengert** [comment]
Ah ok.  Would it hurt anything to include 7 and 8 now and bump the others up by 2?  I guess it's unlikely we'd have to go lower than that.

**Comment by daveismith** [comment]
I mean it's just an enum so you can't really do math or anything with it.
I'm happy to put whatever we want in there (maybe we do a ace, 2, 3, 4, 5,
6, 7, 8, 9, jack, queen, king, joker) so we've got all the cards availabele.

**Review by deadwing88 — APPROVED** [review]
Not sure if we will need the rpc stuff at the bottom, also wonder if classes generated from this giant proto will all end up on a single file as well. Learning process for all of us either way so no worries.

**Pull request merged**
